### ISSUE TITLE
failed to start consumer:  kafka server: Offset's topic has not yet been created.

### ISSUE THREAD

**Issue by Dieterbe** [woodsaj/go-kafka-test#1]
after running start_kafka.sh (i added some echo's to make sure it completes the kafka-topics.sh step), when i run `go run main.go` I get `2016/04/27 17:14:37 failed to start consumer:  kafka server: Offset's topic has not yet been created.
`
this happens when cluster.NewConsumer calls cluster.NewConsumerFromClient

also:

```
~/g/s/g/w/go-kafka-test ❯❯❯ docker exec -t -i kafka bash
root@608a08bb0246:/# /opt/kafka_2.11-0.9.0.1/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 10 --topic test
Error while executing topic command : Topic "test" already exists.
[2016-04-27 21:19:46,428] ERROR kafka.common.TopicExistsException: Topic "test" already exists.
    at kafka.admin.AdminUtils$.createOrUpdateTopicPartitionAssignmentPathInZK(AdminUtils.scala:253)
    at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:237)
    at kafka.admin.TopicCommand$.createTopic(TopicCommand.scala:105)
    at kafka.admin.TopicCommand$.main(TopicCommand.scala:60)
    at kafka.admin.TopicCommand.main(TopicCommand.scala)
 (kafka.admin.TopicCommand$)
root@608a08bb0246:/opt/kafka_2.11-0.9.0.1/bin# ./kafka-topics.sh --list --zookeeper localhost:2181                                                           
test
root@608a08bb0246:/opt/kafka_2.11-0.9.0.1/bin# ./kafka-topics.sh --describe --zookeeper localhost:2181 --topic test
Topic:test  PartitionCount:10   ReplicationFactor:1 Configs:
    Topic: test Partition: 0    Leader: 0   Replicas: 0 Isr: 0
    Topic: test Partition: 1    Leader: 0   Replicas: 0 Isr: 0
    Topic: test Partition: 2    Leader: 0   Replicas: 0 Isr: 0
    Topic: test Partition: 3    Leader: 0   Replicas: 0 Isr: 0
    Topic: test Partition: 4    Leader: 0   Replicas: 0 Isr: 0
    Topic: test Partition: 5    Leader: 0   Replicas: 0 Isr: 0
    Topic: test Partition: 6    Leader: 0   Replicas: 0 Isr: 0
    Topic: test Partition: 7    Leader: 0   Replicas: 0 Isr: 0
    Topic: test Partition: 8    Leader: 0   Replicas: 0 Isr: 0
    Topic: test Partition: 9    Leader: 0   Replicas: 0 Isr: 0
root@608a08bb0246:/opt/kafka_2.11-0.9.0.1/bin# 
```

**Comment by Dieterbe** [comment]
note i had to change

```
-var brokers = []string{"192.168.0.110:9092"}
+var brokers = []string{"172.17.0.2:9092"}
```

because it couldn't connect and that's the ip i see in docker inspect

it makes the producer work but not the consumer.

if i change it to `172.17.0.1:9092` (docker0 ip) it  says `Failed to start Sarama producer: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)`

**Comment by Dieterbe** [comment]
@woodsaj any idea? thx

**Comment by woodsaj** [comment]
make sure the advertised host is being set correctly.

https://github.com/woodsaj/go-kafka-test/blob/master/start_kafka.sh#L3-L5

It should be getting set to the IP address of the docker0 interface. if you add `set -x` to the top of the start_kafka.sh script it will print everything that is happening including what values are being assigned to variables.

**Comment by woodsaj** [comment]
ok. found the problem.  Fixed in 

https://github.com/woodsaj/go-kafka-test/commit/50b2498ede5c30b6318284b47ec0e662111751fa
